#
# OpenSSL/crypto/modes/Makefile
#

DIR=	modes
TOP=	../..
CC=	cc
INCLUDES= -I.. -I$(TOP) -I../../include
CFLAG=-g
MAKEFILE=	Makefile
AR=		ar r

MODES_ASM_OBJ=

CFLAGS= $(INCLUDES) $(CFLAG)
ASFLAGS= $(INCLUDES) $(ASFLAG)
AFLAGS= $(ASFLAGS)

GENERAL=Makefile
TEST=
APPS=

LIB=$(TOP)/libcrypto.a
LIBSRC= cbc128.c ctr128.c cts128.c cfb128.c ofb128.c gcm128.c \
	ccm128.c xts128.c
LIBOBJ= cbc128.o ctr128.o cts128.o cfb128.o ofb128.o gcm128.o \
	ccm128.o xts128.o $(MODES_ASM_OBJ)

SRC= $(LIBSRC)

#EXHEADER= store.h str_compat.h
EXHEADER= modes.h
HEADER=	modes_lcl.h $(EXHEADER)

ALL=    $(GENERAL) $(SRC) $(HEADER)

top:
	(cd ../..; $(MAKE) DIRS=crypto SDIRS=$(DIR) sub_all)

all:	lib

lib:	$(LIBOBJ)
	$(AR) $(LIB) $(LIBOBJ)
	$(RANLIB) $(LIB) || echo Never mind.
	@touch lib

ghash-ia64.s:	asm/ghash-ia64.pl
	$(PERL) asm/ghash-ia64.pl $@ $(CFLAGS)
ghash-x86.s:	asm/ghash-x86.pl
	$(PERL) asm/ghash-x86.pl $(PERLASM_SCHEME) $(CFLAGS) $(PROCESSOR) > $@
ghash-x86_64.s:	asm/ghash-x86_64.pl
	$(PERL) asm/ghash-x86_64.pl $(PERLASM_SCHEME) > $@
ghash-sparcv9.s:	asm/ghash-sparcv9.pl
	$(PERL) asm/ghash-sparcv9.pl $@ $(CFLAGS)
ghash-alpha.s:	asm/ghash-alpha.pl
	(preproc=/tmp/$$$$.$@; trap "rm $$preproc" INT; \
	$(PERL) asm/ghash-alpha.pl > $$preproc && \
	$(CC) -E $$preproc > $@ && rm $$preproc)

ghash-parisc.s:	asm/ghash-parisc.pl
	$(PERL) asm/ghash-parisc.pl $(PERLASM_SCHEME) $@

# GNU make "catch all"
ghash-%.S:	asm/ghash-%.pl;	$(PERL) $< $(PERLASM_SCHEME) $@

ghash-armv4.o:	ghash-armv4.S

files:
	$(PERL) $(TOP)/util/files.pl Makefile >> $(TOP)/MINFO

links:
	@$(PERL) $(TOP)/util/mklink.pl ../../include/openssl $(EXHEADER)
	@$(PERL) $(TOP)/util/mklink.pl ../../test $(TEST)
	@$(PERL) $(TOP)/util/mklink.pl ../../apps $(APPS)

install:
	@[ -n "$(INSTALLTOP)" ] # should be set by top Makefile...
	@headerlist="$(EXHEADER)"; for i in $$headerlist; \
	do  \
	(cp $$i $(INSTALL_PREFIX)$(INSTALLTOP)/include/openssl/$$i; \
	chmod 644 $(INSTALL_PREFIX)$(INSTALLTOP)/include/openssl/$$i ); \
	done;

tags:
	ctags $(SRC)

tests:

lint:
	lint -DLINT $(INCLUDES) $(SRC)>fluff

depend:
	@[ -n "$(MAKEDEPEND)" ] # should be set by upper Makefile...
	$(MAKEDEPEND) -- $(CFLAG) $(INCLUDES) $(DEPFLAG) -- $(PROGS) $(LIBSRC)

dclean:
	$(PERL) -pe 'if (/^# DO NOT DELETE THIS LINE/) {print; exit(0);}' $(MAKEFILE) >Makefile.new
	mv -f Makefile.new $(MAKEFILE)

clean:
	rm -f *.s *.o */*.o *.obj lib tags core .pure .nfs* *.old *.bak fluff

# DO NOT DELETE THIS LINE -- make depend depends on it.
cbc128.o: cbc128.c \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/crypto.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/stdlib.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/cdefs.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/cdefs_elf.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/android/api-level.h \
 /usr/local/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86/lib/gcc/arm-linux-androideabi/4.8/include/stddef.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/string.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/malloc.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/alloca.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/strings.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/stdint.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/machine/_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/_wchar_limits.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/posix_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/stddef.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/compiler.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/asm/posix_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/asm/types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/machine/kernel.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/sysmacros.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/memory.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/e_os2.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/opensslconf.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/stdio.h \
 /usr/local/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86/lib/gcc/arm-linux-androideabi/4.8/include/stdarg.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/stack.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/safestack.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/opensslv.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/ossl_typ.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/symhacks.h \
 modes_lcl.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/modes.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/assert.h
ctr128.o: ctr128.c \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/crypto.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/stdlib.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/cdefs.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/cdefs_elf.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/android/api-level.h \
 /usr/local/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86/lib/gcc/arm-linux-androideabi/4.8/include/stddef.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/string.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/malloc.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/alloca.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/strings.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/stdint.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/machine/_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/_wchar_limits.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/posix_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/stddef.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/compiler.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/asm/posix_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/asm/types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/machine/kernel.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/sysmacros.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/memory.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/e_os2.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/opensslconf.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/stdio.h \
 /usr/local/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86/lib/gcc/arm-linux-androideabi/4.8/include/stdarg.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/stack.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/safestack.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/opensslv.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/ossl_typ.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/symhacks.h \
 modes_lcl.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/modes.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/assert.h
cts128.o: cts128.c \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/crypto.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/stdlib.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/cdefs.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/cdefs_elf.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/android/api-level.h \
 /usr/local/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86/lib/gcc/arm-linux-androideabi/4.8/include/stddef.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/string.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/malloc.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/alloca.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/strings.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/stdint.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/machine/_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/_wchar_limits.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/posix_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/stddef.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/compiler.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/asm/posix_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/asm/types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/machine/kernel.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/sysmacros.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/memory.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/e_os2.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/opensslconf.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/stdio.h \
 /usr/local/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86/lib/gcc/arm-linux-androideabi/4.8/include/stdarg.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/stack.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/safestack.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/opensslv.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/ossl_typ.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/symhacks.h \
 modes_lcl.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/modes.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/assert.h
cfb128.o: cfb128.c \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/crypto.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/stdlib.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/cdefs.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/cdefs_elf.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/android/api-level.h \
 /usr/local/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86/lib/gcc/arm-linux-androideabi/4.8/include/stddef.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/string.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/malloc.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/alloca.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/strings.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/stdint.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/machine/_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/_wchar_limits.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/posix_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/stddef.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/compiler.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/asm/posix_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/asm/types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/machine/kernel.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/sysmacros.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/memory.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/e_os2.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/opensslconf.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/stdio.h \
 /usr/local/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86/lib/gcc/arm-linux-androideabi/4.8/include/stdarg.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/stack.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/safestack.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/opensslv.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/ossl_typ.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/symhacks.h \
 modes_lcl.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/modes.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/assert.h
ofb128.o: ofb128.c \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/crypto.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/stdlib.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/cdefs.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/cdefs_elf.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/android/api-level.h \
 /usr/local/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86/lib/gcc/arm-linux-androideabi/4.8/include/stddef.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/string.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/malloc.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/alloca.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/strings.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/stdint.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/machine/_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/_wchar_limits.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/posix_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/stddef.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/compiler.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/asm/posix_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/asm/types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/machine/kernel.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/sysmacros.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/memory.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/e_os2.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/opensslconf.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/stdio.h \
 /usr/local/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86/lib/gcc/arm-linux-androideabi/4.8/include/stdarg.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/stack.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/safestack.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/opensslv.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/ossl_typ.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/symhacks.h \
 modes_lcl.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/modes.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/assert.h
ccm128.o: ccm128.c \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/crypto.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/stdlib.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/cdefs.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/cdefs_elf.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/android/api-level.h \
 /usr/local/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86/lib/gcc/arm-linux-androideabi/4.8/include/stddef.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/string.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/malloc.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/alloca.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/strings.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/stdint.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/machine/_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/_wchar_limits.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/posix_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/stddef.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/compiler.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/asm/posix_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/asm/types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/machine/kernel.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/sysmacros.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/memory.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/e_os2.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/opensslconf.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/stdio.h \
 /usr/local/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86/lib/gcc/arm-linux-androideabi/4.8/include/stdarg.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/stack.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/safestack.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/opensslv.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/ossl_typ.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/symhacks.h \
 modes_lcl.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/modes.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/assert.h
xts128.o: xts128.c \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/crypto.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/stdlib.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/cdefs.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/cdefs_elf.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/android/api-level.h \
 /usr/local/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86/lib/gcc/arm-linux-androideabi/4.8/include/stddef.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/string.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/malloc.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/alloca.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/strings.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/stdint.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/machine/_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/_wchar_limits.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/posix_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/stddef.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/compiler.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/asm/posix_types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/asm/types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/linux/types.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/machine/kernel.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/sys/sysmacros.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/memory.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/e_os2.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/opensslconf.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/stdio.h \
 /usr/local/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86/lib/gcc/arm-linux-androideabi/4.8/include/stdarg.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/stack.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/safestack.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/opensslv.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/ossl_typ.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/symhacks.h \
 modes_lcl.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/openssl/modes.h \
 /usr/local/android-ndk/platforms/android-9/arch-arm/usr/include/assert.h
